models/Adminer.php
<?php

namespace Gaolei\YiiRBAC\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\ForbiddenHttpException;
use yii\web\IdentityInterface;
use yii\web\Response;

/**
 * Adminer model
 */
class Adminer extends \Gaolei\YiiRBAC\models\map\Adminer implements IdentityInterface
{

    /**
     * @inheritdoc
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'state' => static::STATE_ACTIVE]);
    }

    /**
     * @inheritdoc
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey(): string
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey): bool
    {
        return $this->getAuthKey() === $authKey;
    }
}

models/BizRule.php
<?php

namespace Gaolei\YiiRBAC\models;

use Yii;
use yii\rbac\Rule;
use Gaolei\YiiRBAC\components\Configs;

/**
 * BizRule
 *
 * @author Misbahul D Munir <misbahuldmunir@gmail.com>
 * @since 1.0
 */
class BizRule extends \yii\base\Model
{
    /**
     * @var string name of the rule
     */
    public $name;

    /**
     * @var integer UNIX timestamp representing the rule creation time
     */
    public $createdAt;

    /**
     * @var integer UNIX timestamp representing the rule updating time
     */
    public $updatedAt;

    /**
     * @var string Rule classname.
     */
    public $className;

    /**
     * @var Rule
     */
    private $_item;

    /**
     * Initialize object
     * @param \yii\rbac\Rule $item
     * @param array $config
     */
    public function __construct($item, $config = [])
    {
        $this->_item = $item;
        if ($item !== null) {
            $this->name = $item->name;
            $this->className = get_class($item);
        }
        parent::__construct($config);
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'className'], 'required'],
            [['className'], 'string'],
            [['className'], 'classExists']
        ];
    }

    /**
     * Validate class exists
     */
    public function classExists()
    {
        if (!class_exists($this->className)) {
            $message = Yii::t('rbac-admin', "Unknown class '{class}'", ['class' => $this->className]);
            $this->addError('className', $message);
            return;
        }
        if (!is_subclass_of($this->className, Rule::className())) {
            $message = Yii::t('rbac-admin', "'{class}' must extend from 'yii\rbac\Rule' or its child class", [
                    'class' => $this->className]);
            $this->addError('className', $message);
        }
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'name' => Yii::t('rbac-admin', 'Name'),
            'className' => Yii::t('rbac-admin', 'Class Name'),
        ];
    }

    /**
     * Check if new record.
     * @return boolean
     */
    public function getIsNewRecord()
    {
        return $this->_item === null;
    }

    /**
     * Find model by id
     * @param type $id
     * @return null|static
     */
    public static function find($id)
    {
        $item = Configs::authManager()->getRule($id);
        if ($item !== null) {
            return new static($item);
        }
        return null;
    }

    /**
     * Save model to authManager
     * @return boolean
     */
    public function save()
    {
        if ($this->validate()) {
            $manager = Configs::authManager();
            $class = $this->className;
            if ($this->_item === null) {
                $this->_item = new $class();
                $isNew = true;
            } else {
                $isNew = false;
                $oldName = $this->_item->name;
            }
            $this->_item->name = $this->name;
            if ($isNew) {
                $manager->add($this->_item);
            } else {
                $manager->update($oldName, $this->_item);
            }
            return true;
        }
        return false;
    }

    /**
     * Get item
     * @return Item
     */
    public function getItem()
    {
        return $this->_item;
    }
}

controllers/AdminerController.php
<?php

namespace Gaolei\YiiRBAC\controllers;

use Yii;
use yii\base\UserException;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use Gaolei\YiiRBAC\models\form\ChangePwd;
use Gaolei\YiiRBAC\models\form\Login;
use Gaolei\YiiRBAC\models\form\Signup;
use Gaolei\YiiRBAC\models\search\AdminerSearch;
use Gaolei\YiiRBAC\models\Adminer;

/**
 * User controller
 */
class AdminerController extends Controller
{

    private $_oldMailPath;

    private $admin;

    public function init()
    {
        parent::init();
        $this->admin = \Yii::$app->user->identity;
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['post'],
                    'logout' => ['post'],
                    'activate' => ['post'],
                ],
            ],
        ];
    }

    /**
     * 检查是否能够操作账户
     * @param Adminer $user
     * @return bool
     * @author gaolei 2021/10/7 7:46 下午
     */
    protected function canOperate(Adminer $user): bool
    {
        if($this->admin->id !== 1){
            if ($user->id === $this->admin->getId()) {
                Yii::$app->session->setFlash('error', "管理员不能修改自己的账号");
                return false;
            } elseif ($user->id === 1) {
                Yii::$app->session->setFlash('error', "超级管理员不可修改");
                return false;
            } elseif ($this->admin->level < $user->level) {
                Yii::$app->session->setFlash('error', "你没有权限进行此操作");
                return false;
            }
        }
        return true;
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AdminerSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', ['model' => $this->findModel($id),]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $user = $this->findModel($id);
        if ($this->canOperate($user)) {
            if ($user->delete()) {
                \Yii::$app->session->setFlash('success', '操作成功');
            } else {
                \Yii::$app->session->setFlash('danger', '操作失败');
            }
        }
        return $this->redirect(['index']);
    }

    /**
     * Login
     */
    public function actionLogin()
    {
        if (!Yii::$app->getUser()->isGuest) {
            return $this->goHome();
        }
        $model = new Login();
        if ($model->load(Yii::$app->getRequest()->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', ['model' => $model,]);
    }

    /**
     * Logout
     */
    public function actionLogout()
    {
        Yii::$app->getUser()->logout();
        return $this->goHome();
    }

    /**
     * Signup new user
     */
    public function actionSignup()
    {
        if ($this->admin->level < $this->admin::LEVE_ADMIN) {
            \Yii::$app->session->setFlash('warning', '没有权限进行该操作');
            return $this->goHome();
        }
        $model = new Signup();
        if ($model->load(Yii::$app->getRequest()->post()) && $model->signup()) {
            return $this->redirect(['index']);
        }
        return $this->render('signup', ['model' => $model,]);
    }

    /**
     * 重置账号密码
     */
    public function actionResetPwd(int $id, string $pwd)
    {
        if ($this->admin->level < $this->admin::LEVE_ADMIN) {
            \Yii::$app->session->setFlash('warning', '没有权限进行该操作');
            return $this->goHome();
        }
        if (!preg_match('/^[0-9A-Za-z]{6,16}$/', $pwd)) {
            \Yii::$app->session->setFlash('warning', '密码必须是由字母、数字组成的字符串[6~16]');

        }else{
            if ($user = $this->findModel($id)) {
                if (!$this->admin->id !== 1 && $this->admin->level <= $user->level) {
                    \Yii::$app->session->setFlash('warning', '没有权限进行该操作');
                } else {
                    $user->setPassword($pwd);
                    $user->generateAuthKey();
                    if ($user->save(false)) {
                        \Yii::$app->session->setFlash('success', '密码重置成功');
                    } else {
                        \Yii::$app->session->setFlash('error', '密码重置失败');
                    }
                }
            } else {
                \Yii::$app->session->setFlash('danger', '要操作的账户不存在');
            }
        }
        return $this->goBack();
    }

    /**
     * 修改当前账户密码
     */
    public function actionUpdatePwd()
    {
        $model = new ChangePwd();
        if ($model->load(Yii::$app->getRequest()->post()) && $model->updatePwd()) {
            return $this->goBack();
        }
        return $this->render('update-pwd', ['model' => $model]);
    }

    /**
     * 激活账户
     * @param integer $id
     * @return \yii\web\Response
     * @throws NotFoundHttpException
     * @throws UserException
     */
    public function actionActive(int $id): \yii\web\Response
    {
        if ($this->admin->level < $this->admin::LEVE_ADMIN) {
            return $this->goHome();
        }
        /* @var $user Adminer */
        $user = $this->findModel($id);
        if ($this->canOperate($user) && $user->state !== Adminer::STATE_ACTIVE) {
            $user->state = Adminer::STATE_ACTIVE;
            if (!$user->save()) {
                $errors = $user->firstErrors;
                throw new UserException(reset($errors));
            }
        }
        return $this->redirect(['index']);
    }

    /**
     * 禁用账户
     * @param integer $id
     * @return \yii\web\Response
     * @throws NotFoundHttpException
     * @throws UserException
     */
    public function actionDisable(int $id): \yii\web\Response
    {
        if ($this->admin->level < $this->admin::LEVE_ADMIN) {
            return $this->goHome();
        }
        /* @var $user Adminer */
        $user = $this->findModel($id);
        if ($this->canOperate($user) && $user->state !== Adminer::STATE_DISABLE) {
            $user->state = Adminer::STATE_DISABLE;
            if (!$user->save()) {
                $errors = $user->firstErrors;
                throw new UserException(reset($errors));
            }
        }
        return $this->redirect(['index']);
    }

    /**
     * @param $id
     * @return Adminer|null
     * @throws NotFoundHttpException
     * @author gaolei 2021/10/7 12:06 上午
     */
    protected function findModel($id): Adminer
    {
        if (($model = Adminer::findOne($id)) !== null) {
            return $model;
        }
        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/adminer/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model Gaolei\YiiRBAC\models\Adminer */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'status')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('rbac-admin', 'Create') : Yii::t('rbac-admin', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/adminer/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\bootstrap\ActiveForm;
use Gaolei\YiiRBAC\models\Adminer;
use Gaolei\YiiRBAC\components\Helper;

/* @var $this yii\web\View */
/* @var $searchModel Gaolei\YiiRBAC\models\search\AdminerSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = '账号管理';
$this->params['breadcrumbs'][] = $this->title;

$levels = Adminer::levels();
$states = Adminer::states();
\yii\web\YiiAsset::register($this);
$this->registerJs($this->render('_script.js'), $this::POS_HEAD);
$admin = \Yii::$app->getUser()->identity;
?>
<div class="page-container">

    <div class="page-search">
        <?php $form = ActiveForm::begin(['action' => ['index'], 'method' => 'get', 'id' => 'page-search-form']); ?>
        <?= Html::activeInput('text', $searchModel, 'id', ['class' => 'form-control w80 dis-in-b', 'placeholder' => 'ID']) ?>
        <?= Html::activeInput('text', $searchModel, 'username', ['class' => 'form-control w100 dis-in-b', 'placeholder' => '登录名']) ?>
        <?= Html::activeInput('text', $searchModel, 'realname', ['class' => 'form-control w150 dis-in-b', 'placeholder' => '姓名']) ?>
        <?= Html::activeInput('text', $searchModel, 'phone', ['class' => 'form-control w150 dis-in-b', 'placeholder' => '手机']) ?>
        <?= Html::submitButton('搜索', ['class' => 'btn btn-primary']) ?>
        <?php ActiveForm::end(); ?>
        <?= Html::a('添加账号', ['signup'], ['class' => 'btn btn-success']) ?>
    </div>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'id',
            'username',
            'realname',
            'phone',
            [
                'label' => '权限等级',
                'attribute' => 'level',
                'value' => function ($model) use ($levels) {
                    return $levels[$model->level];
                },
                'filter' => $levels
            ],
            [
                'attribute' => 'state',
                'format' => 'raw',
                'value' => function ($model) use ($states) {
                    $class = 'text-success';
                    if ($model->state === Adminer::STATE_DISABLE) {
                        $class = 'text-warning';
                    }
                    return '<span class="' . $class . '">' . $states[$model->state] . '</span>';
                },
                'filter' => $states
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => Helper::filterActionColumn(['allot', 'active', 'disable', 'reset-pwd', 'view', 'delete']),
                'buttons' => [
                    'allot' => function ($url, $model) use ($admin) {
                        if ($admin->getId() === 1 || $admin->level > $model->level) {
                            return Html::a('授权', ['/admin/allot?id=' . $model->id], [
                                'class' => 'btn btn-xs btn-info'
                            ]);
                        }
                    },
                    'reset-pwd' => function ($url, $model) use ($admin) {
                        if ($admin->level > $model->level) {
                            return Html::button('重置密码', [
                                'class' => 'btn btn-xs btn-primary',
                                'onClick' => "resetPwd('{$model->id}')"
                            ]);
                        }
                        return '';
                    },
                    'active' => function ($url, $model) use ($admin) {
                        if (
                            $model->state === Adminer::STATE_ACTIVE ||
                            $admin->level <= $model->level
                        ) {
                            return '';
                        }
                        $options = [
                            'title' => '激活',
                            'aria-label' => '激活',
                            'data-confirm' => '确认激活此账户？',
                            'data-method' => 'post',
                            'data-pjax' => '0',
                            'class' => 'btn btn-xs btn-success'
                        ];
                        return Html::a('激活', $url, $options);
                    },
                    'disable' => function ($url, $model) use ($admin) {
                        if (
                            $model->state == Adminer::STATE_DISABLE ||
                            $admin->level <= $model->level
                        ) {
                            return '';
                        }
                        $options = [
                            'title' => '禁用',
                            'aria-label' => '禁用',
                            'data-confirm' => '确认禁用此账户？',
                            'data-method' => 'post',
                            'data-pjax' => '0',
                            'class' => 'btn btn-xs btn-warning'
                        ];
                        return Html::a('禁用', $url, $options);
                    }
                ]
            ],
        ],
    ]); ?>
</div>

views/adminer/login.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/** @var \Gaolei\YiiRBAC\models\form\Signup $model */

$this->title = '登录';
$fieldOptions1 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-envelope form-control-feedback'></span>"
];
$fieldOptions2 = [
    'options' => ['class' => 'form-group has-feedback'],
    'inputTemplate' => "{input}<span class='glyphicon glyphicon-lock form-control-feedback'></span>"
];
?>
<div class="login-box">
    <div class="login-logo">
        <a href="#"><b><?= \Yii::$app->name ?></b></a>
    </div>
    <div class="login-box-body">
        <p class="login-box-msg"><?=$this->title?></p>
        <?php $form = ActiveForm::begin(['id' => 'login-form', 'enableClientValidation' => false]); ?>
        <?= $form->field($model, 'username', $fieldOptions1)->label(false)
            ->textInput(['placeholder' => $model->getAttributeLabel('username')]) ?>
        <?= $form->field($model, 'password', $fieldOptions2)->label(false)
            ->passwordInput(['placeholder' => $model->getAttributeLabel('password')]) ?>
        <div class="row">
            <div class="col-xs-8">
                <?= $form->field($model, 'rememberMe')->checkbox() ?>
            </div>
            <div class="col-xs-4">
                <?= Html::submitButton('登录', ['class' => 'btn btn-primary btn-block btn-flat', 'name' => 'login-button']) ?>
            </div>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>

views/adminer/signup.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/**
 * @var $this yii\web\View
 * @var $form yii\bootstrap\ActiveForm
 * @var $model \Gaolei\YiiRBAC\models\form\Signup
 */
$this->title = '添加账户';
$this->params['breadcrumbs'][] = ['label' => '账户管理', 'url' => 'index'];
$this->params['breadcrumbs'][] = $this->title;
$levels = \Gaolei\YiiRBAC\models\Adminer::levels();
$admin = \Yii::$app->user->identity;
if ($admin->getId() > 1) {
    foreach ($levels as $k => $str) {
        if ($k >= $admin->level) {
            unset($levels[$k]);
        }
    }
}
?>
<div class="page-container">
    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>
            <?= $form->field($model, 'username')->label('登陆名')->textInput(['autofocus' => true]) ?>
            <?= $form->field($model, 'realname')->label('真实姓名') ?>
            <?= $form->field($model, 'phone')->label('联系电话') ?>
            <?= $form->field($model, 'level')->label('权限等级')->dropDownList($levels) ?>
            <?= $form->field($model, 'password')->label('密码')->passwordInput() ?>
            <div class="form-group">
                <?= Html::submitButton('添加', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/adminer/update-pwd.php
<?php

use yii\web\View;
use yii\widgets\ActiveForm;
use Gaolei\YiiRBAC\models\form\ChangePwd;

/** @var View $this */
/** @var ChangePwd $model */
$this->title = '更新密码';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="page-container">
    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>
            <?= $form->field($model, 'old_pass')->label('原密码')->passwordInput(['autofocus' => true]) ?>
            <?= $form->field($model, 'new_pass')->label('新密码')->passwordInput() ?>
            <?= $form->field($model, 'con_pass')->label('确认密码')->passwordInput() ?>
            <div class="form-group">
                <?= \yii\helpers\Html::submitButton('保存', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/adminer/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use Gaolei\YiiRBAC\components\Helper;

/* @var $this yii\web\View */
/* @var $model Gaolei\YiiRBAC\models\Adminer */

$this->title = $model->username;
$this->params['breadcrumbs'][] = ['label' => '账户管理', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

$controllerId = $this->context->uniqueId . '/';
$levels = $model::levels();
$states = $model::states();
?>
<div class="page-container">
    <p>
        <?php
        if ($model->state == $model::STATE_DISABLE && Helper::checkRoute($controllerId . 'activate')) {
            echo Html::a(Yii::t('rbac-admin', 'Activate'), ['activate', 'id' => $model->id], [
                'class' => 'btn btn-primary',
                'data' => [
                    'confirm' => Yii::t('rbac-admin', 'Are you sure you want to activate this user?'),
                    'method' => 'post',
                ],
            ]);
        }
        ?>
        <?php
        if (Helper::checkRoute($controllerId . 'delete')) {
            echo Html::a(Yii::t('rbac-admin', 'Delete'), ['delete', 'id' => $model->id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => Yii::t('yii', 'Are you sure you want to delete this item?'),
                    'method' => 'post',
                ],
            ]);
        }
        ?>
    </p>
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'username',
            'realname',
            'phone',
            [
                'label' => '权限等级',
                'attribute' => 'level',
                'value' => function ($model) use ($levels) {
                    return $levels[$model->level];
                },
                'filter' => $levels
            ],
            [
                'label' => '权限等级',
                'attribute' => 'level',
                'value' => function ($model) use ($states) {
                    return $states[$model->state];
                },
                'filter' => $states
            ],
            'created_at:datetime',
            'updated_at:datetime',
        ],
    ]) ?>
</div>